name: fake_process_manager
description: Process Manager for faking processes in tests. Taken from Flutter Tools.
version: 0.2.0
homepage: https://github.com/jonasbadstuebner/fake_process_manager
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  process: ^5.0.3
  tool_base:
    git: https://github.com/jonasbadstuebner/tool_base.git
    # path: /home/jbadstuebner/Dokumente/git/github.com/jonasbadstuebner/tool_base/main
  mockito: ^5.4.0
  test: ">=1.22.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  tool_base_test:
    git: https://github.com/jonasbadstuebner/tool_base_test.git
    # path: /home/jbadstuebner/Dokumente/git/github.com/jonasbadstuebner/tool_base_test/main
